module.exports = function (deployer: Truffle.Deployer) {
  const DexNewsContract = artifacts.require('DexNews');
  const DomToken = artifacts.require('DOMToken');
  const categories = ['economy', 'tech', 'government'];
  const countries = [
    'cn',
    'in',
    'us',
    'id',
    'pk',
    'ng',
    'br',
    'bd',
    'ru',
    'mx',
    'jp',
    'ph',
    'et',
    'eg',
    'cd',
    'vn',
    'ir',
    'tr',
    'de',
    'th',
    'fr',
    'gb',
    'it',
    'tz',
    'za',
    'ke',
    'kr',
    'es',
    'co',
    'sd',
    'ar',
    'ua',
    'ug',
    'dz',
    'iq',
    'pl',
    'ca',
    'af',
    'ma',
    'sa',
    'my',
    'ao',
    'pe',
    'uz',
    'np',
    'mz',
    'ye',
    'gh',
    've',
  ];
  deployer.deploy(DexNewsContract, DomToken.address, categories, countries);
} as Truffle.Migration;
